services:
  db:
    image: postgres:16
    container_name: demoapp_db
    environment:
      POSTGRES_DB: demoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - demoapp_pgdata:/var/lib/postgresql/data

volumes:
  demoapp_pgdata:
